#!/bin/sh
# Licence compliance for the ONNX base image: writes out/THIRD-PARTY.tsv (every package
# in the image with version and licence) and out/sources/<package>-<version>.tar.gz for
# every package under a copyleft licence (GPL, LGPL, MPL): Alpine's build recipe
# (APKBUILD + patches from aports) plus the upstream source it builds from. Publish
# these next to the image; that is how we offer the corresponding source.
#
#   ./sources.sh
set -eu

ALPINE=3.24.2
OUT="$(cd "$(dirname "$0")" && pwd)/out"
mkdir -p "$OUT/sources"

docker run --rm --platform linux/arm64 -v "$OUT:/out" "alpine:$ALPINE" sh -euc '
    apk add -q --no-cache python3 py3-onnxruntime py3-numpy openssl dropbear curl >/dev/null
    # Package, version, licence and origin (source package) from the apk database.
    awk "/^P:/{p=substr(\$0,3)} /^V:/{v=substr(\$0,3)} /^L:/{l=substr(\$0,3)} /^o:/{o=substr(\$0,3)}
         /^$/{if (p) print p\"\t\"v\"\t\"l\"\t\"o; p=\"\"}" /lib/apk/db/installed | sort > /out/packages.tsv
    { printf "package\tversion\tlicense\n"; cut -f1-3 /out/packages.tsv;
      printf "tokenizers (PyPI)\t0.23.2\tApache-2.0\n"; } > /out/THIRD-PARTY.tsv
'

# Copyleft source packages; zstd is dual BSD-3-Clause OR GPL, we take BSD.
grep -iE 'GPL|MPL' "$OUT/packages.tsv" | grep -v '^zstd' | awk -F'\t' '{print $4"\t"$2}' | sort -u > "$OUT/copyleft.tsv"
cat "$OUT/copyleft.tsv"

docker run --rm --platform linux/arm64 -v "$OUT:/out" "alpine:$ALPINE" sh -euc '
    apk add -q --no-cache alpine-sdk >/dev/null
    adduser -D builder && addgroup builder abuild
    su builder -c "abuild-keygen -a -n >/dev/null 2>&1" || true
    cd /tmp
    wget -q "https://gitlab.alpinelinux.org/alpine/aports/-/archive/v3.24.2/aports-v3.24.2.tar.gz" -O aports.tar.gz
    tar xzf aports.tar.gz && chown -R builder aports-v3.24.2
    while IFS="$(printf "\t")" read -r origin version; do
        dir=$(ls -d aports-v3.24.2/*/"$origin" 2>/dev/null | head -1)
        [ -n "$dir" ] || { echo "no aports recipe for $origin" >&2; continue; }
        out="/out/sources/$origin-$version.tar.gz"
        [ -f "$out" ] && continue
        su builder -c "cd $dir && SRCDEST=\$PWD/distfiles abuild fetch >/dev/null" || echo "fetch failed: $origin" >&2
        tar czf "$out" -C "$(dirname "$dir")" "$origin"
        echo "$out"
    done < /out/copyleft.tsv
'
cat > "$OUT/SOURCE.md" <<'MD'
# Acurast ONNX base image (Alpine 3.24.2, aarch64): sources and licences

`acurast-onnx-alpine3.24.2-aarch64.tar.xz` is an Alpine Linux 3.24.2 root filesystem with
Python 3.14, ONNX Runtime 1.24.4, numpy, tokenizers 0.23.2 (from PyPI), openssl,
dropbear and curl, built by `images/onnx/build.sh` in
https://github.com/Acurast/acurast-example-apps.

- `THIRD-PARTY.tsv` lists every package in the image with its version and licence
  (from Alpine's package database, plus tokenizers from PyPI, Apache-2.0).
- `sources/<package>-<version>.tar.gz` is the corresponding source for every package under
  a copyleft licence (GPL, LGPL, MPL): Alpine's build recipe (APKBUILD and patches from
  aports, tag v3.24.2) and the upstream source it builds from. Generated by
  `images/onnx/sources.sh`. zstd is dual-licensed and used under BSD-3-Clause.
- The binaries themselves are Alpine's official packages for v3.24.2 (aarch64); their
  sources are also at https://gitlab.alpinelinux.org/alpine/aports/-/tree/v3.24.2.
MD
ls -l "$OUT/sources"
